spring.application.name=em

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/em?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=Y3Jpc3RpYW5KRXBlU2VjdXJlSldUS2V5MjAyNkBlbXBsb3llTWVuYWdlbWVudA==
jwt.expiration=86400000
